### ISSUE TITLE
zenpower/0.2.0 and kernel 6.16

### ISSUE THREAD

**Issue by Dany-Wilde** [ocerman/zenpower#53]
zenpower3 (zenpower/0.2.0) is not compatible  with kernel 6.16 .
Here are the logs:

 https://debian-facile.org/viewtopic.php?pid=432727#p432727
 
 zenpower working on kernel 6.12
 installation of kernel 6.16 :
 
> Installation de :
>   linux-image-6.16.0-amd64
> 
> Sommaire :
>   Mise à niveau de : 0. Installation de : 1Supprimé : 0. Non mis à jour : 2
> Taille du téléchargement : 0 B / 161 MB
>   Espace nécessaire : 258 MB / 67,4 GB disponible
> 
> Réception de : 1 /home/alain/compilation/linux-image-6.16.0-amd64_6.16-1_amd64.deb linux-image-6.16.0-amd64 amd64 6.16-1 [161 MB]
> Sélection du paquet linux-image-6.16.0-amd64 précédemment désélectionné.
> (Lecture de la base de données... 561270 fichiers et répertoires déjà installés.
> )
> Préparation du dépaquetage de .../linux-image-6.16.0-amd64_6.16-1_amd64.deb ...
> Dépaquetage de linux-image-6.16.0-amd64 (6.16-1) ...
> Paramétrage de linux-image-6.16.0-amd64 (6.16-1) ...
> Sign command: /lib/modules/6.16.0-amd64/build/scripts/sign-file
> Signing key: /var/lib/dkms/mok.key
> Public certificate (MOK): /var/lib/dkms/mok.pub
> 
> Autoinstall of module virtualbox/7.1.12 for kernel 6.16.0-amd64 (x86_64)
> Building module(s).... done.
> Signing module /var/lib/dkms/virtualbox/7.1.12/build/vboxdrv/vboxdrv.ko
> Signing module /var/lib/dkms/virtualbox/7.1.12/build/vboxnetadp/vboxnetadp.ko
> Signing module /var/lib/dkms/virtualbox/7.1.12/build/vboxnetflt/vboxnetflt.ko
> Installing /lib/modules/6.16.0-amd64/updates/dkms/vboxdrv.ko.xz
> Installing /lib/modules/6.16.0-amd64/updates/dkms/vboxnetadp.ko.xz
> Installing /lib/modules/6.16.0-amd64/updates/dkms/vboxnetflt.ko.xz
> Running depmod.... done.
> 
> Autoinstall of module zenpower/0.2.0 for kernel 6.16.0-amd64 (x86_64)
> Building module(s)...(bad exit status: 2)
> Failed command:
> make -j24 KERNELRELEASE=6.16.0-amd64 TARGET=6.16.0-amd64 CFLAGS_MODULE+=
> 
> Error! Bad return status for module build on kernel: 6.16.0-amd64 (x86_64)
> Consult /var/lib/dkms/zenpower/0.2.0/build/make.log for more information.
> 
> Autoinstall on 6.16.0-amd64 succeeded for module(s) virtualbox.
> Autoinstall on 6.16.0-amd64 failed for module(s) zenpower(10).
> 
> Error! One or more modules failed to install during autoinstall.
> Refer to previous errors for more information.
> run-parts: /etc/kernel/postinst.d/dkms exited with return code 1
> update-initramfs: Generating /boot/initrd.img-6.16.0-amd64
> Generating grub configuration file ...
> Found background image: /usr/share/images/desktop-base/desktop-grub.png
> Found linux image: /boot/vmlinuz-6.16.0-amd64
> Found initrd image: /boot/initrd.img-6.16.0-amd64
> Found linux image: /boot/vmlinuz-6.12.38+deb13-amd64
> Found initrd image: /boot/initrd.img-6.12.38+deb13-amd64
> Found linux image: /boot/vmlinuz-6.12.37+deb13-amd64
> Found initrd image: /boot/initrd.img-6.12.37+deb13-amd64
> Found linux image: /boot/vmlinuz-6.12.33+deb13-amd64
> Found initrd image: /boot/initrd.img-6.12.33+deb13-amd64
> Found memtest86+ 64bit EFI image: /boot/memtest86+x64.efi
> Found memtest86+ 32bit EFI image: /boot/memtest86+ia32.efi
> Found memtest86+ 64bit image: /boot/memtest86+x64.bin
> Found memtest86+ 32bit image: /boot/memtest86+ia32.bin
> Warning: os-prober will be executed to detect other bootable partitions.
> Its output will be used to detect bootable binaries on them and create new boot
> entries.
> Found Windows Boot Manager on /dev/nvme1n1p1@/efi/Microsoft/Boot/bootmgfw.efi
> Found Debian GNU/Linux 12 (bookworm) on /dev/sdb2
> Adding boot menu entry for UEFI Firmware Settings ...
> done
> dpkg: erreur de traitement du paquet linux-image-6.16.0-amd64 (--configure) :
>  le sous-processus paquet linux-image-6.16.0-amd64 script post-installation inst
> allé a renvoyé un état de sortie d'erreur 1
> Des erreurs ont été rencontrées pendant l'exécution :
>  linux-image-6.16.0-amd64
> Notification : Le téléchargement est effectué en dehors du bac à sable en tant que superutilisateur car le fichier « /home/alain/compilation/linux-image-6.16.0-amd64_6.16-1_amd64.deb » n'est pas accessible par l'utilisateur « _apt ». - pkgAcquire::Run (13: Permission non accordée)
> Erreur : Sub-process /usr/bin/dpkg returned an error code (1)
> 

compilation of the zenpower module  under kernel 6.16 :

 @sid:~/Téléchargements/zenpower3$ sudo make dkms-install

> dkms --version >> /dev/null
> mkdir -p /usr/src/zenpower-0.2.0
> cp /home/alain/Téléchargements/zenpower3/dkms.conf /usr/src/zenpower-0.2.0
> cp /home/alain/Téléchargements/zenpower3/Makefile /usr/src/zenpower-0.2.0
> cp /home/alain/Téléchargements/zenpower3/zenpower.c /usr/src/zenpower-0.2.0
> sed -e "s/@CFLGS@//" \
>     -e "s/@VERSION@/0.2.0/" \
>     -i /usr/src/zenpower-0.2.0/dkms.conf
> dkms add zenpower/0.2.0
> Creating symlink /var/lib/dkms/zenpower/0.2.0/source -> /usr/src/zenpower-0.2.0
> dkms build zenpower/0.2.0
> Sign command: /lib/modules/6.16.0-amd64/build/scripts/sign-file
> Signing key: /var/lib/dkms/mok.key
> Public certificate (MOK): /var/lib/dkms/mok.pub
> 
> Building module(s)...(bad exit status: 2)
> Failed command:
> make -j24 KERNELRELEASE=6.16.0-amd64 TARGET=6.16.0-amd64 CFLAGS_MODULE+=
> 
> Error! Bad return status for module build on kernel: 6.16.0-amd64 (x86_64)
> Consult /var/lib/dkms/zenpower/0.2.0/build/make.log for more information.
> make: *** [Makefile:40: dkms-install] Error 10
> 
> 

logs :

 sudo less /var/lib/dkms/zenpower/0.2.0/build/make.log
 
> DKMS (dkms-3.2.0) make.log for zenpower/0.2.0 for kernel 6.16.0-amd64 (x86_64)
> mar. 05 août 2025 02:15:28 CEST
> 
> Building module(s)
> ## command: make -j24 KERNELRELEASE=6.16.0-amd64 TARGET=6.16.0-amd64 CFLAGS_MODULE+=
> make[1] : on entre dans le répertoire « /usr/src/linux-headers-6.16.0-amd64 »
> make[2] : on entre dans le répertoire « /var/lib/dkms/zenpower/0.2.0/build »
>   CC [M]  zenpower.o
> zenpower.c:38:10: fatal error: asm/amd_nb.h: Aucun fichier ou dossier de ce nom
>    38 | #include <asm/amd_nb.h>
>       |          ^~~~~~~~~~~~~~
> compilation terminated.
> make[4]: *** [/usr/src/linux-headers-6.16.0-amd64/scripts/Makefile.build:287: zenpower.o] Error 1
> make[3]: *** [/usr/src/linux-headers-6.16.0-amd64/Makefile:2003: .] Error 2
> make[2]: *** [/usr/src/linux-headers-6.16.0-amd64/Makefile:248: __sub-make] Error 2
> make[2] : on quitte le répertoire « /var/lib/dkms/zenpower/0.2.0/build »
> make[1]: *** [Makefile:248: __sub-make] Error 2
> make[1] : on quitte le répertoire « /usr/src/linux-headers-6.16.0-amd64 »
> make: *** [Makefile:27: modules] Error 2
> 
> ## exit code: 2
> ## elapsed time: 00:00:01
> ----------------------------------------------------------------
> /var/lib/dkms/zenpower/0.2.0/build/make.log (END)
> 

modification of the offending line :

head -n 40 /var/lib/dkms/zenpower/0.2.0/build/zenpower.c
 
> /*
>  * Zenpower - Driver for reading temperature, voltage, current and power for AMD 17h CPUs
>  *
>  * Copyright (c) 2018-2021 Anthony Wang
>  *
>  * This driver is free software; you can redistribute it and/or
>  * modify it under the terms of the GNU General Public License; either
>  * version 2 of the License, or (at your option) any later version.
>  *
>  * This driver is distributed in the hope that it will be useful,
>  * but WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
>  * See the GNU General Public License for more details.
>  *
>  * You should have received a copy of the GNU General Public License
>  * along with this driver; if not, see <http://www.gnu.org/licenses/>.
>  *
>  */
> 
> /*
>  * forked from the original zenpower by Ondrej Čerman
>  *
>  * based on k10temp by Clemens Ladisch
>  *
>  * Docs:
>  *  - https://www.kernel.org/doc/Documentation/hwmon/hwmon-kernel-api.txt
>  *  - https://developer.amd.com/wp-content/resources/56255_3_03.PDF
>  *
>  * Sources:
>  *  - Temp monitoring is from k10temp
>  *  - SVI address and voltage formula is from LibreHardwareMonitor
>  *  - Current formulas and CCD temp addresses were discovered experimentally
>  */
> 
> #include <linux/hwmon.h>
> #include <linux/module.h>
> #include <linux/pci.h>
> // #include <asm/amd_nb.h>
> 
> MODULE_DESCRIPTION("AMD ZEN family CPU Sensors Driver");
> 
> .../... 
> 

If this does not change anything under kernel 6.12, 
it does not change anything under kernel 6.16 either. 
Zenpower refuses to compile and  install under the new kernel.
