### ISSUE TITLE
Can't compile - kernel warning

### ISSUE THREAD

**Issue by senar030** [ocerman/zenpower#56]
Hi. I was trying to compile, but I got an error:

> XXX:~/zenpower$ sudo make dkms-install
mkdir /usr/src/zenpower-0.1.12
cp /home/senar/zenpower/dkms.conf /usr/src/zenpower-0.1.12
cp /home/senar/zenpower/Makefile /usr/src/zenpower-0.1.12
cp /home/senar/zenpower/zenpower.c /usr/src/zenpower-0.1.12
sed -e "s/@CFLGS@//" \
    -e "s/@VERSION@/0.1.12/" \
    -i /usr/src/zenpower-0.1.12/dkms.conf
dkms add zenpower/0.1.12
Creating symlink /var/lib/dkms/zenpower/0.1.12/source -> /usr/src/zenpower-0.1.12
dkms build zenpower/0.1.12
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der
Building module:
Cleaning build area...
make -j12 KERNELRELEASE=6.14.0-37-generic TARGET=6.14.0-37-generic CFLAGS_MODULE+=...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.14.0-37-generic (x86_64)
Consult /var/lib/dkms/zenpower/0.1.12/build/make.log for more information.
make: *** [Makefile:39: dkms-install] Fehler 10

Here is the /var/lib/dkms/zenpower/0.1.12/build/make.log:

> DKMS make.log for zenpower-0.1.12 for kernel 6.14.0-37-generic (x86_64)
Mo 2. Feb 11:09:17 CET 2026
make[1]: Verzeichnis „/var/lib/dkms/zenpower/0.1.12/build“ wird betreten
make[2]: Verzeichnis „/usr/src/linux-headers-6.14.0-37-generic“ wird betreten
make[3]: Verzeichnis „/var/lib/dkms/zenpower/0.1.12/build“ wird betreten
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  zenpower.o
zenpower.c:211:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
  211 | int static debug_addrs_arr[] = {
      | ^~~
zenpower.c: In function ‘zenpower_probe’:
zenpower.c:553:41: error: implicit declaration of function ‘amd_pci_dev_to_node_id’ [-Werror=implicit-function-declaration]
  553 |                         data->node_id = amd_pci_dev_to_node_id(pdev);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~
zenpower.c: In function ‘zenpower_read’:
zenpower.c:281:33: warning: this statement may fall through [-Wimplicit-fallthrough=]
  281 |                         channel -= 1;   // hwmon_in have different indexing, see note at zenpower_info
      |                         ~~~~~~~~^~~~
zenpower.c:284:17: note: here
  284 |                 case hwmon_curr:
      |                 ^~~~
zenpower.c: In function ‘kernel_smn_read’:
zenpower.c:452:9: warning: ignoring return value of ‘amd_smn_read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  452 |         amd_smn_read(node_id, address, regval);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[5]: *** [/usr/src/linux-headers-6.14.0-37-generic/scripts/Makefile.build:207: zenpower.o] Fehler 1
make[4]: *** [/usr/src/linux-headers-6.14.0-37-generic/Makefile:1997: .] Fehler 2
make[3]: *** [/usr/src/linux-headers-6.14.0-37-generic/Makefile:251: __sub-make] Fehler 2
make[3]: Verzeichnis „/var/lib/dkms/zenpower/0.1.12/build“ wird verlassen
make[2]: *** [Makefile:251: __sub-make] Fehler 2
make[2]: Verzeichnis „/usr/src/linux-headers-6.14.0-37-generic“ wird verlassen
make[1]: *** [Makefile:27: modules] Fehler 2
make[1]: Verzeichnis „/var/lib/dkms/zenpower/0.1.12/build“ wird verlassen

I am new to this stuff. So please forgive me if I am asking a stupid question.
